language: node_js
node_js:
  - 'stable'

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    - 'node_modules'
    - '/home/travis/.cache/Cypress'

script:
  - yarn unit-test
  - yarn e2e-prod

# safelist
branches:
  only:
    - master
    - development
    - /feat\/.*/
