language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
    - '/home/travis/.cache/Cypress'

script:
  - yarn e2e:dev-webpack
  - yarn e2e:prod

# safelist
branches:
  only:
    - master
    - v4.1
