language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
    - "/home/travis/.cache/Cypress"

script:
  - yarn e2e:prod
  - yarn e2e:dev-webpack

# safelist
branches:
  only:
  - master
	- development
  - /.*(hotfix|feature).*$/
