version: 2.1
jobs:
  build:
    docker:
      # - image: circleci/node:10
      - image: cypress/base:8
    working_directory: ~/zap
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Test
          command: echo 'oi' $CIRCLE_PULL_REQUEST $CIRCLE_BRANCH
  build_dev:
    docker:
      # - image: circleci/node:10
      - image: cypress/base:8
    working_directory: ~/zap
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Test
          command: echo 'oi' $CIRCLE_PULL_REQUEST $CIRCLE_BRANCH

workflows:
  version: 2.1

  conditional-workflow:
    when:
      or: # All must be true to trigger
        - equal: [master, << pipeline.git.branch >>]
        - equal: [development, << pipeline.git.branch >>]
        - equal: [true, $CIRCLE_PULL_REQUEST]

    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - build_dev:
          filters:
            branches:
              only:
                - development
