version: 2
jobs:
  build:
    docker:
      # - image: circleci/node:10
      - image: cypress/base:8
    working_directory: ~/zap
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installation
          command: yarn
      - run:
          name: Running Unit Tests
          command: yarn unit-test
      - run:
          name: Running E2E tests
          command: yarn e2e-prod

  deploy-prod:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Pushing to Heroku
          command: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PROD_ZAP.git

  deploy-dev:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy 'development' to Heroku
          command: git push  https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_DEV_ZAP.git

workflows:
  version: 2

  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - developmet
            #     - /feat\/.*/
            # tags:
            #   only: /^v.*/
      # - deploy-dev:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only:
      #           - development
      # - deploy-prod:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         ignore: /.*/
      #       tags:
      #         only: /^v.*/
