version: 2.1

commands:
  ignore_all_other_branches:
    steps:
      - run:
          name: Early return if this build is from a forked PR
          command: |
            if [ -n "$CIRCLE_PULL_REQUEST" ]; then
              echo "Nothing to do for forked PRs, so marking this step successful"
              circleci-agent step halt

            fi

jobs:
  build:
    docker:
      # - image: circleci/node:10
      - image: cypress/base:8
    working_directory: ~/zap
    steps:
      - ignore_all_other_branches
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Test
          command: echo 'oi' $CIRCLE_PULL_REQUEST $CIRCLE_BRANCH

      - run: echo << parameters.node-version >>
  build_dev:
    docker:
      # - image: circleci/node:10
      - image: cypress/base:8
    working_directory: ~/zap
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Test
          command: echo 'oi' $CIRCLE_PULL_REQUEST $CIRCLE_BRANCH

workflows:
  version: 2.1

  conditional-workflow:
    when:
      or: # All must be true to trigger
        - equal: [master, << pipeline.git.branch >>]
        - equal: [development, << pipeline.git.branch >>]
        - equal: [true, $CIRCLE_PULL_REQUEST]
        - equal: [true, '$CIRCLE_PULL_REQUEST']
        - equal: [true, CIRCLE_PULL_REQUEST]
        - << pipeline.parameters.run-deploy >>
        # - $CIRCLE_PULL_REQUEST
        # - '$CIRCLE_PULL_REQUEST'

  jobs:
    - build:
        node-version: 10
        filters:
          branches:
            only:
              - master
  #   - build_dev:
  #       filters:
  #         branches:
  #           only:
  #             - development
