version: 2
jobs:
#   deploy-development:
#     - run:
#         name: Deploy Development branch to Heroku
#         command: git push f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master:development
#   deploy-master:
#     - run:
#         name: Deploy Development branch to Heroku
        command: git push f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  deploy-prod:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy master to Heroku
          command: git push f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  build:
    docker:
      # - image: circleci/node:10
      - image: cypress/base:8
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installation
          command: yarn
      - run:
          name: Running E2E tests
          command: yarn e2e:prod
      - run:
          name: Deploy Master branch to Heroku
          command: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
          
#   deploy:
#     docker:
#       - image: buildpack-deps:trusty
#     steps:
#       - checkout
#       - run:
#           name: Deploy master to Heroku
#           command: git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-dev:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - development
                - /(feature|hotfix)\/.*/
      - deploy-prod:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - master
#       - build
#       - deploy:
#           requires:
#             - build
