version: 2
jobs:
  build:
    docker:
      - image: cypress/base:8
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installation
          command: yarn
      - run:
          name: Running E2E tests
          command: |
            yarn e2e-dev-webpack
            yarn e2e-prod

  deploy-prod:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy master to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_PROD_WEBPACK_BOILERPLATE.git master

  deploy-dev:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy 'development' to Heroku
          command: |
            git push -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_DEV_WEBPACK_BOILERPLATE.git development:master

workflows:
  version: 2

  build-deploy:
    jobs:
      - build
      # - deploy-dev:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only:
      #           - development
      #           - /(feature|hotfix)\/.*/
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
