version: 2

jobs:
  build:
    docker:
      # - image: circleci/node:10
      - image: cypress/base:8
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Installation
          command: yarn
      - run:
          name: Running E2E tests
          command: yarn e2e:prod
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
        name: Deploy to Heroku (Development Branch)
        command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git feature/circleci-deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: feature/circleci-deploy
